; generated by Thumb C Compiler, ADS1.2 [Build 805]

; commandline [-fpu None -O2 -Otime -S -apcs /interwork -Wb]
        CODE16

        AREA ||.text||, CODE, READONLY

first PROC
        LDR      r1,|L1.992|
        ADD      r2,r0,r1
        LDR      r1,|L1.992| + 4
        STR      r2,[r1,#0]  ; gLits
        LDR      r2,|L1.992| + 8
        ADD      r2,r0,r2
        STR      r2,[r1,#4]  ; gLits
        LDR      r2,|L1.992| + 12
        ADD      r2,r0,r2
        STR      r2,[r1,#8]  ; gLits
        LDR      r2,|L1.992| + 16
        ADD      r2,r0,r2
        STR      r2,[r1,#0xc]  ; gLits
        LDR      r2,|L1.992| + 20
        ADD      r2,r0,r2
        STR      r2,[r1,#0x10]  ; gLits
        LDR      r2,|L1.992| + 24
        ADD      r2,r0,r2
        STR      r2,[r1,#0x14]  ; gLits
        LDR      r2,|L1.992| + 28
        ADD      r2,r0,r2
        STR      r2,[r1,#0x18]  ; gLits
        LDR      r2,|L1.992| + 32
        ADD      r2,r0,r2
        STR      r2,[r1,#0x1c]  ; gLits
        LDR      r2,|L1.992| + 36
        ADD      r2,r0,r2
        STR      r2,[r1,#0x20]  ; gLits
        LDR      r2,|L1.992| + 40
        ADD      r0,r0,r2
        STR      r0,[r1,#0x24]  ; gLits
        BX       lr
        ENDP

big PROC
        LDR      r1,|L1.992| + 44
        PUSH     {r4}
        MOV      r3,#1
        MOV      r2,r0
        EOR      r2,r3
        LDR      r1,[r1,#0]  ; gBuffer
        MOV      r3,#2
        STMIA    r1!,{r0,r2}
        MOV      r2,r0
        EOR      r2,r3
        SUB      r1,#8
        STR      r2,[r1,#8]
        MOV      r2,r0
        MOV      r3,#3
        EOR      r2,r3
        STR      r2,[r1,#0xc]
        MOV      r2,r0
        MOV      r3,#4
        EOR      r2,r3
        STR      r2,[r1,#0x10]
        MOV      r2,r0
        MOV      r3,#5
        EOR      r2,r3
        STR      r2,[r1,#0x14]
        MOV      r2,r0
        MOV      r3,#6
        EOR      r2,r3
        STR      r2,[r1,#0x18]
        MOV      r2,r0
        MOV      r3,#7
        EOR      r2,r3
        STR      r2,[r1,#0x1c]
        MOV      r2,r0
        MOV      r3,#8
        EOR      r2,r3
        STR      r2,[r1,#0x20]
        MOV      r2,r0
        MOV      r3,#9
        EOR      r2,r3
        STR      r2,[r1,#0x24]
        MOV      r2,r0
        MOV      r3,#0xa
        EOR      r2,r3
        STR      r2,[r1,#0x28]
        MOV      r2,r0
        MOV      r3,#0xb
        EOR      r2,r3
        STR      r2,[r1,#0x2c]
        MOV      r2,r0
        MOV      r3,#0xc
        EOR      r2,r3
        STR      r2,[r1,#0x30]
        MOV      r2,r0
        MOV      r3,#0xd
        EOR      r2,r3
        STR      r2,[r1,#0x34]
        MOV      r2,r0
        MOV      r3,#0xe
        EOR      r2,r3
        STR      r2,[r1,#0x38]
        MOV      r2,r0
        MOV      r3,#0xf
        EOR      r2,r3
        STR      r2,[r1,#0x3c]
        MOV      r2,r0
        MOV      r3,#0x10
        EOR      r2,r3
        STR      r2,[r1,#0x40]
        MOV      r2,r0
        MOV      r3,#0x11
        EOR      r2,r3
        STR      r2,[r1,#0x44]
        MOV      r2,r0
        MOV      r3,#0x12
        EOR      r2,r3
        STR      r2,[r1,#0x48]
        MOV      r2,r0
        MOV      r3,#0x13
        EOR      r2,r3
        STR      r2,[r1,#0x4c]
        MOV      r2,r0
        MOV      r3,#0x14
        EOR      r2,r3
        STR      r2,[r1,#0x50]
        MOV      r2,r0
        MOV      r3,#0x15
        EOR      r2,r3
        STR      r2,[r1,#0x54]
        MOV      r2,r0
        MOV      r3,#0x16
        EOR      r2,r3
        STR      r2,[r1,#0x58]
        MOV      r2,r0
        MOV      r3,#0x17
        EOR      r2,r3
        STR      r2,[r1,#0x5c]
        MOV      r2,r0
        MOV      r3,#0x18
        EOR      r2,r3
        STR      r2,[r1,#0x60]
        MOV      r2,r0
        MOV      r3,#0x19
        EOR      r2,r3
        STR      r2,[r1,#0x64]
        MOV      r2,r0
        MOV      r3,#0x1a
        EOR      r2,r3
        STR      r2,[r1,#0x68]
        MOV      r2,r0
        MOV      r3,#0x1b
        EOR      r2,r3
        STR      r2,[r1,#0x6c]
        MOV      r2,r0
        MOV      r3,#0x1c
        EOR      r2,r3
        STR      r2,[r1,#0x70]
        MOV      r2,r0
        MOV      r3,#0x1d
        EOR      r2,r3
        STR      r2,[r1,#0x74]
        MOV      r2,r0
        MOV      r3,#0x1e
        EOR      r2,r3
        STR      r2,[r1,#0x78]
        MOV      r2,r0
        MOV      r3,#0x1f
        EOR      r2,r3
        STR      r2,[r1,#0x7c]
        MOV      r2,#0x20
        MOV      r3,r0
        EOR      r3,r2
        MOV      r2,r1
        ADD      r2,#0x80
        STR      r3,[r2,#0]
        MOV      r3,r0
        MOV      r4,#0x21
        EOR      r3,r4
        STR      r3,[r2,#4]
        MOV      r3,r0
        MOV      r4,#0x22
        EOR      r3,r4
        STR      r3,[r2,#8]
        MOV      r3,r0
        MOV      r4,#0x23
        EOR      r3,r4
        STR      r3,[r2,#0xc]
        MOV      r3,r0
        MOV      r4,#0x24
        EOR      r3,r4
        STR      r3,[r2,#0x10]
        MOV      r3,r0
        MOV      r4,#0x25
        EOR      r3,r4
        STR      r3,[r2,#0x14]
        MOV      r3,r0
        MOV      r4,#0x26
        EOR      r3,r4
        STR      r3,[r2,#0x18]
        MOV      r3,r0
        MOV      r4,#0x27
        EOR      r3,r4
        STR      r3,[r2,#0x1c]
        MOV      r3,r0
        MOV      r4,#0x28
        EOR      r3,r4
        STR      r3,[r2,#0x20]
        MOV      r3,r0
        MOV      r4,#0x29
        EOR      r3,r4
        STR      r3,[r2,#0x24]
        MOV      r3,r0
        MOV      r4,#0x2a
        EOR      r3,r4
        STR      r3,[r2,#0x28]
        MOV      r3,r0
        MOV      r4,#0x2b
        EOR      r3,r4
        STR      r3,[r2,#0x2c]
        MOV      r3,r0
        MOV      r4,#0x2c
        EOR      r3,r4
        STR      r3,[r2,#0x30]
        MOV      r3,r0
        MOV      r4,#0x2d
        EOR      r3,r4
        STR      r3,[r2,#0x34]
        MOV      r3,r0
        MOV      r4,#0x2e
        EOR      r3,r4
        STR      r3,[r2,#0x38]
        MOV      r3,r0
        MOV      r4,#0x2f
        EOR      r3,r4
        STR      r3,[r2,#0x3c]
        MOV      r3,r0
        MOV      r2,#0x30
        EOR      r3,r2
        MOV      r2,r1
        ADD      r2,#0xc0
        MOV      r4,#0x31
        STR      r3,[r2,#0]
        MOV      r3,r0
        EOR      r3,r4
        STR      r3,[r2,#4]
        MOV      r3,r0
        MOV      r4,#0x32
        EOR      r3,r4
        STR      r3,[r2,#8]
        MOV      r3,r0
        MOV      r4,#0x33
        EOR      r3,r4
        STR      r3,[r2,#0xc]
        MOV      r3,r0
        MOV      r4,#0x34
        EOR      r3,r4
        STR      r3,[r2,#0x10]
        MOV      r3,r0
        MOV      r4,#0x35
        EOR      r3,r4
        STR      r3,[r2,#0x14]
        MOV      r3,r0
        MOV      r4,#0x36
        EOR      r3,r4
        STR      r3,[r2,#0x18]
        MOV      r3,r0
        MOV      r4,#0x37
        EOR      r3,r4
        STR      r3,[r2,#0x1c]
        MOV      r3,r0
        MOV      r4,#0x38
        EOR      r3,r4
        STR      r3,[r2,#0x20]
        MOV      r3,r0
        MOV      r4,#0x39
        EOR      r3,r4
        STR      r3,[r2,#0x24]
        MOV      r3,r0
        MOV      r4,#0x3a
        EOR      r3,r4
        STR      r3,[r2,#0x28]
        MOV      r3,r0
        MOV      r4,#0x3b
        EOR      r3,r4
        STR      r3,[r2,#0x2c]
        MOV      r3,r0
        MOV      r4,#0x3c
        EOR      r3,r4
        STR      r3,[r2,#0x30]
        MOV      r3,r0
        MOV      r4,#0x3d
        EOR      r3,r4
        STR      r3,[r2,#0x34]
        MOV      r3,r0
        MOV      r4,#0x3e
        EOR      r3,r4
        STR      r3,[r2,#0x38]
        MOV      r3,r0
        MOV      r4,#0x3f
        EOR      r3,r4
        STR      r3,[r2,#0x3c]
        MOV      r3,r0
        MOV      r2,#0x40
        EOR      r3,r2
        MOV      r2,r1
        ADD      r2,#0xff
        ADD      r2,#1
        STR      r3,[r2,#0]
        MOV      r3,r0
        MOV      r4,#0x41
        EOR      r3,r4
        STR      r3,[r2,#4]
        MOV      r3,r0
        MOV      r4,#0x42
        EOR      r3,r4
        STR      r3,[r2,#8]
        MOV      r3,r0
        MOV      r4,#0x43
        EOR      r3,r4
        STR      r3,[r2,#0xc]
        MOV      r3,r0
        MOV      r4,#0x44
        EOR      r3,r4
        STR      r3,[r2,#0x10]
        MOV      r3,r0
        MOV      r4,#0x45
        EOR      r3,r4
        STR      r3,[r2,#0x14]
        MOV      r3,r0
        MOV      r4,#0x46
        EOR      r3,r4
        STR      r3,[r2,#0x18]
        MOV      r3,r0
        MOV      r4,#0x47
        EOR      r3,r4
        STR      r3,[r2,#0x1c]
        MOV      r3,r0
        MOV      r4,#0x48
        EOR      r3,r4
        STR      r3,[r2,#0x20]
        MOV      r3,r0
        MOV      r4,#0x49
        EOR      r3,r4
        STR      r3,[r2,#0x24]
        MOV      r3,r0
        MOV      r4,#0x4a
        EOR      r3,r4
        STR      r3,[r2,#0x28]
        MOV      r3,r0
        MOV      r4,#0x4b
        EOR      r3,r4
        STR      r3,[r2,#0x2c]
        MOV      r3,r0
        MOV      r4,#0x4c
        EOR      r3,r4
        STR      r3,[r2,#0x30]
        MOV      r3,r0
        MOV      r4,#0x4d
        EOR      r3,r4
        STR      r3,[r2,#0x34]
        MOV      r3,r0
        MOV      r4,#0x4e
        EOR      r3,r4
        STR      r3,[r2,#0x38]
        MOV      r3,r0
        MOV      r4,#0x4f
        EOR      r3,r4
        STR      r3,[r2,#0x3c]
        MOV      r3,r0
        MOV      r2,#0x50
        EOR      r3,r2
        MOV      r2,r1
        ADD      r2,#0xff
        ADD      r2,#0x41
        STR      r3,[r2,#0]
        MOV      r3,r0
        MOV      r4,#0x51
        EOR      r3,r4
        STR      r3,[r2,#4]
        MOV      r3,r0
        MOV      r4,#0x52
        EOR      r3,r4
        STR      r3,[r2,#8]
        MOV      r3,r0
        MOV      r4,#0x53
        EOR      r3,r4
        STR      r3,[r2,#0xc]
        MOV      r3,r0
        MOV      r4,#0x54
        EOR      r3,r4
        STR      r3,[r2,#0x10]
        MOV      r3,r0
        MOV      r4,#0x55
        EOR      r3,r4
        STR      r3,[r2,#0x14]
        MOV      r3,r0
        MOV      r4,#0x56
        EOR      r3,r4
        STR      r3,[r2,#0x18]
        MOV      r3,r0
        MOV      r4,#0x57
        EOR      r3,r4
        STR      r3,[r2,#0x1c]
        MOV      r3,r0
        MOV      r4,#0x58
        EOR      r3,r4
        STR      r3,[r2,#0x20]
        MOV      r3,r0
        MOV      r4,#0x59
        EOR      r3,r4
        STR      r3,[r2,#0x24]
        MOV      r3,r0
        MOV      r4,#0x5a
        EOR      r3,r4
        STR      r3,[r2,#0x28]
        MOV      r3,r0
        MOV      r4,#0x5b
        EOR      r3,r4
        STR      r3,[r2,#0x2c]
        MOV      r3,r0
        MOV      r4,#0x5c
        EOR      r3,r4
        STR      r3,[r2,#0x30]
        MOV      r3,r0
        MOV      r4,#0x5d
        EOR      r3,r4
        STR      r3,[r2,#0x34]
        MOV      r3,r0
        MOV      r4,#0x5e
        EOR      r3,r4
        STR      r3,[r2,#0x38]
        MOV      r3,r0
        MOV      r4,#0x5f
        EOR      r3,r4
        STR      r3,[r2,#0x3c]
        MOV      r2,r0
        MOV      r3,#0x60
        ADD      r1,#0xff
        ADD      r1,#0x81
        EOR      r2,r3
        MOV      r3,#0x61
        STR      r2,[r1,#0]
        MOV      r2,r0
        EOR      r2,r3
        STR      r2,[r1,#4]
        MOV      r2,r0
        MOV      r3,#0x62
        EOR      r2,r3
        STR      r2,[r1,#8]
        MOV      r2,r0
        MOV      r3,#0x63
        EOR      r2,r3
        STR      r2,[r1,#0xc]
        MOV      r2,r0
        MOV      r3,#0x64
        EOR      r2,r3
        STR      r2,[r1,#0x10]
        MOV      r2,r0
        MOV      r3,#0x65
        EOR      r2,r3
        STR      r2,[r1,#0x14]
        MOV      r2,r0
        MOV      r3,#0x66
        EOR      r2,r3
        STR      r2,[r1,#0x18]
        MOV      r2,r0
        MOV      r3,#0x67
        EOR      r2,r3
        STR      r2,[r1,#0x1c]
        MOV      r2,r0
        MOV      r3,#0x68
        EOR      r2,r3
        STR      r2,[r1,#0x20]
        CMP      r0,#7
        BEQ      |L1.988|
        MOV      r3,#0x69
        MOV      r2,r0
        EOR      r2,r3
        STR      r2,[r1,#0x24]
        MOV      r2,r0
        MOV      r3,#0x6a
        EOR      r2,r3
        STR      r2,[r1,#0x28]
        MOV      r2,r0
        MOV      r3,#0x6b
        EOR      r2,r3
        STR      r2,[r1,#0x2c]
        MOV      r2,r0
        MOV      r3,#0x6c
        EOR      r2,r3
        STR      r2,[r1,#0x30]
        MOV      r2,r0
        MOV      r3,#0x6d
        EOR      r2,r3
        STR      r2,[r1,#0x34]
        MOV      r2,r0
        MOV      r3,#0x6e
        EOR      r2,r3
        STR      r2,[r1,#0x38]
        MOV      r2,r0
        MOV      r3,#0x6f
        EOR      r2,r3
        STR      r2,[r1,#0x3c]
|L1.988|
        B        |L1.1040|
        DCW      0000
|L1.992| DATA
        DCD      0x00012345
        DCD      gLits
        DCD      0x00013456
        DCD      0x00014567
        DCD      0x00015678
        DCD      0x00016789
        DCD      0x0001789a
        DCD      0x000189ab
        DCD      0x00019abc
        DCD      0x0001abcd
        DCD      0x0001bcde
        DCD      gBuffer
|L1.1040|
        LDR      r1,|L1.1068|
        ADD      r0,r0,r1
        LDR      r1,|L1.1068| + 4
        STR      r0,[r1,#0]  ; gSecond
        POP      {r4}
        BX       lr
        ENDP

last PROC
        LDR      r0,|L1.1068| + 8
        LDR      r1,|L1.1068| + 12
        LDR      r0,[r0,#0]  ; gThird
        ADD      r0,r0,r1
        LDR      r1,|L1.1068| + 4
        STR      r0,[r1,#0]  ; gSecond
        BX       lr
        DCW      0000
|L1.1068| DATA
        DCD      0x00022222
        DCD      gSecond
        DCD      gThird
        DCD      0x00054321
        ENDP



        EXPORT last
        EXPORT big
        EXPORT first

        IMPORT gThird
        IMPORT gSecond
        IMPORT gBuffer
        IMPORT gLits
        IMPORT ||Lib$$Request$$armlib||, WEAK

        KEEP ||BuildAttributes$$THUMB_ISAv1$M$A:L22$X:L11$S22$IW$~STKCKD$~SHL$OTIME$PRES8||
||BuildAttributes$$THUMB_ISAv1$M$A:L22$X:L11$S22$IW$~STKCKD$~SHL$OTIME$PRES8|| EQU 0

        ASSERT {ENDIAN} = "little"
        ASSERT {SWST} = {FALSE}
        ASSERT {NOSWST} = {TRUE}
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {NOT_SHL} = {TRUE}
        ASSERT {FULL_IEEE} = {FALSE}
        ASSERT {SHL1} = {FALSE}
        ASSERT {SHL2} = {FALSE}
        END
