; generated by Thumb C Compiler, ADS1.2 [Build 805]

; commandline [-fpu None -O2 -Otime -S -apcs /interwork -Wb -Iinclude]
        CODE16

        AREA text, CODE, READONLY

sub_803FB24 PROC
        STR      r1,[r0,#0]
        CMP      r3,#0xff
        BNE      %12
        LDR      r1,_0803FB50
        LDR      r1,[r1,#0]  ; gUnknown_03003E88
        LDRB     r3,[r1,#0x14]
12
        LDRH     r1,[r0,#0x10]
        LSL      r3,r3,#26
        LSR      r1,r1,#6
        LSL      r1,r1,#6
        LSR      r3,r3,#26
        ORR      r1,r3
        STRH     r1,[r0,#0x10]
        STRB     r2,[r0,#4]
        LDR      r2,_0803FB54
        MOV      r1,#0
        STR      r1,[r0,#8]
        STRH     r2,[r0,#0xc]
        STRH     r2,[r0,#0xe]
        STR      r1,[r0,#0x14]
        STR      r1,[r0,#0x18]
        BX       lr
        ENDP
_0803FB50 DCD      gUnknown_03003E88
_0803FB54 DCD      0x0000fffe



        EXPORT sub_803FB24

        IMPORT gUnknown_03003E88
        IMPORT ||Lib$$Request$$armlib||, WEAK

        KEEP ||BuildAttributes$$THUMB_ISAv1$M$A:L22$X:L11$S22$IW$~STKCKD$~SHL$OTIME$PRES8||
||BuildAttributes$$THUMB_ISAv1$M$A:L22$X:L11$S22$IW$~STKCKD$~SHL$OTIME$PRES8|| EQU 0

        ASSERT {ENDIAN} = "little"
        ASSERT {SWST} = {FALSE}
        ASSERT {NOSWST} = {TRUE}
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {NOT_SHL} = {TRUE}
        ASSERT {FULL_IEEE} = {FALSE}
        ASSERT {SHL1} = {FALSE}
        ASSERT {SHL2} = {FALSE}
        END
