; generated by Thumb C++ Compiler, ADS1.2 [Build 805]

; commandline [-fpu None -O2 -Otime -S -apcs /interwork -Wb -Iinclude]
        CODE16

        AREA ||.text||, CODE, READONLY

__ct__13dword_803E67CFv PROC
        PUSH     {r3,lr}
        CMP      r0,#0
        BNE      |L1.16|
        MOV      r0,#0x24
        BL       __nw__FUi
        CMP      r0,#0
        BEQ      |L1.20|
|L1.16|
        LDR      r1,|L1.28|
        STR      r1,[r0,#0]
|L1.20|
        ADD      sp,#4
        POP      {r3}
        BX       r3
        DCW      0000
|L1.28| DATA
        DCD      __VTABLE__13dword_803E67C
        ENDP


        CODE32

        AREA __VTABLE__13dword_803E67C, COMDEF, CODE, READONLY

        DCD      __dt__13dword_803E67CFv - {PC}

        AREA ||i.__dt__13dword_803E67CFv||, COMDEF, CODE, READONLY

        CODE16

__dt__13dword_803E67CFv PROC
        PUSH     {r3-r5,lr}
        MOV      r4,r0
        MOV      r5,r1
        MOV      r1,#0
        BL       __dt__14Singleton_3E80Fv
        CMP      r5,#0
        BEQ      |L3.22|
        MOV      r0,r4
        BL       __dl__FPv
|L3.22|
        POP      {r3-r5}
        POP      {r3}
        BX       r3
        ENDP



        EXPORT __dt__13dword_803E67CFv
        EXPORT __VTABLE__13dword_803E67C
        EXPORT __ct__13dword_803E67CFv

        IMPORT __dt__14Singleton_3E80Fv
        IMPORT __dl__FPv
        IMPORT __nw__FUi
        IMPORT ||Lib$$Request$$cpplib||, WEAK
        IMPORT ||Lib$$Request$$armlib||, WEAK

        KEEP ||BuildAttributes$$THUMB_ISAv1$M$A:L22$X:L11$S22$IW$~STKCKD$~SHL$OTIME$PRES8||
||BuildAttributes$$THUMB_ISAv1$M$A:L22$X:L11$S22$IW$~STKCKD$~SHL$OTIME$PRES8|| EQU 0

        ASSERT {ENDIAN} = "little"
        ASSERT {SWST} = {FALSE}
        ASSERT {NOSWST} = {TRUE}
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {NOT_SHL} = {TRUE}
        ASSERT {FULL_IEEE} = {FALSE}
        ASSERT {SHL1} = {FALSE}
        ASSERT {SHL2} = {FALSE}
        END
