; generated by Thumb C++ Compiler, ADS1.2 [Build 805]

; commandline [-fpu None -O2 -Otime -S -apcs /interwork -Wb -Iinclude]
        CODE16

        AREA text, CODE, READONLY

sub_80402F8 PROC
        PUSH     {r3-r5,lr}
        MOV      r4,r0
        LDR      r0,[r0,#0x30]
        MOV      r5,r1
        CMP      r0,#0
        BEQ      %68
        LDRH     r0,[r4,#0xe]
        LSL      r1,r0,#31
        BMI      %28
        LSL      r0,r0,#28
        BPL      %42
        LDR      r0,[r4,#0x48]
        CMP      r0,#0
        BNE      %42
28
        LDR      r1,[r4,#0]
        MOV      r0,r4
        LDR      r2,[r1,#0x4c]
        ADD      r2,r2,r1
        MOV      r1,r5
        BL       __call_via_r2
42
        LDRH     r0,[r4,#0xe]
        LSL      r0,r0,#28
        BPL      %68
        LDR      r0,[r4,#0x48]
        CMP      r0,#0
        BEQ      %68
        LDR      r1,[r4,#0]
        MOV      r0,r4
        LDR      r2,[r1,#0x58]
        ADD      r2,r2,r1
        MOV      r1,r5
        BL       __call_via_r2
68
        LDRH     r0,[r4,#0xe]
        LSL      r0,r0,#30
        BPL      %88
        LDR      r1,[r4,#0]
        MOV      r0,r4
        LDR      r2,[r1,#0x50]
        ADD      r2,r2,r1
        MOV      r1,r5
        BL       __call_via_r2
88
        LDRH     r0,[r4,#0xe]
        LSL      r0,r0,#29
        BPL      %108
        LDR      r1,[r4,#0]
        MOV      r0,r4
        LDR      r2,[r1,#0x54]
        ADD      r2,r2,r1
        MOV      r1,r5
        BL       __call_via_r2
108
        POP      {r3-r5}
        POP      {r3}
        BX       r3
        ENDP
        DCW      0000



        EXPORT sub_80402F8

        IMPORT __call_via_r2
        IMPORT ||Lib$$Request$$cpplib||, WEAK
        IMPORT ||Lib$$Request$$armlib||, WEAK

        KEEP ||BuildAttributes$$THUMB_ISAv1$M$A:L22$X:L11$S22$IW$~STKCKD$~SHL$OTIME$PRES8||
||BuildAttributes$$THUMB_ISAv1$M$A:L22$X:L11$S22$IW$~STKCKD$~SHL$OTIME$PRES8|| EQU 0

        ASSERT {ENDIAN} = "little"
        ASSERT {SWST} = {FALSE}
        ASSERT {NOSWST} = {TRUE}
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {NOT_SHL} = {TRUE}
        ASSERT {FULL_IEEE} = {FALSE}
        ASSERT {SHL1} = {FALSE}
        ASSERT {SHL2} = {FALSE}
        END
