; generated by Thumb C++ Compiler, ADS1.2 [Build 805]

; commandline [-fpu None -O2 -Otime -S -apcs /interwork -Wb -Iinclude]
        CODE16

        AREA ||.text||, CODE, READONLY

sub_80402F8 PROC
        PUSH     {r3-r5,lr}
        MOV      r4,r0
        LDR      r0,[r0,#0x30]
        MOV      r5,r1
        CMP      r0,#0
        BEQ      |L1.68|
        LDRH     r0,[r4,#0xe]
        LSL      r1,r0,#31
        BMI      |L1.28|
        LSL      r0,r0,#28
        BPL      |L1.42|
        LDR      r0,[r4,#0x48]
        CMP      r0,#0
        BNE      |L1.42|
|L1.28|
        LDR      r0,[r4,#0]
        LDR      r1,[r0,#0x4c]
        ADD      r2,r0,r1
        MOV      r1,r5
        MOV      r0,r4
        BL       __call_via_r2
|L1.42|
        LDRH     r0,[r4,#0xe]
        LSL      r0,r0,#28
        BPL      |L1.68|
        LDR      r0,[r4,#0x48]
        CMP      r0,#0
        BEQ      |L1.68|
        LDR      r0,[r4,#0]
        LDR      r1,[r0,#0x58]
        ADD      r2,r0,r1
        MOV      r1,r5
        MOV      r0,r4
        BL       __call_via_r2
|L1.68|
        LDRH     r0,[r4,#0xe]
        LSL      r0,r0,#30
        BPL      |L1.88|
        LDR      r0,[r4,#0]
        LDR      r1,[r0,#0x50]
        ADD      r2,r0,r1
        MOV      r1,r5
        MOV      r0,r4
        BL       __call_via_r2
|L1.88|
        LDRH     r0,[r4,#0xe]
        LSL      r0,r0,#29
        BPL      |L1.108|
        LDR      r0,[r4,#0]
        LDR      r1,[r0,#0x54]
        ADD      r2,r0,r1
        MOV      r1,r5
        MOV      r0,r4
        BL       __call_via_r2
|L1.108|
        POP      {r3-r5}
        POP      {r3}
        BX       r3
        DCW      0000
        ENDP



        EXPORT sub_80402F8

        IMPORT __call_via_r2
        IMPORT ||Lib$$Request$$cpplib||, WEAK
        IMPORT ||Lib$$Request$$armlib||, WEAK

        KEEP ||BuildAttributes$$THUMB_ISAv1$M$A:L22$X:L11$S22$IW$~STKCKD$~SHL$OTIME$PRES8||
||BuildAttributes$$THUMB_ISAv1$M$A:L22$X:L11$S22$IW$~STKCKD$~SHL$OTIME$PRES8|| EQU 0

        ASSERT {ENDIAN} = "little"
        ASSERT {SWST} = {FALSE}
        ASSERT {NOSWST} = {TRUE}
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {NOT_SHL} = {TRUE}
        ASSERT {FULL_IEEE} = {FALSE}
        ASSERT {SHL1} = {FALSE}
        ASSERT {SHL2} = {FALSE}
        END
