; generated by Thumb C++ Compiler, ADS1.2 [Build 805]

; commandline [-fpu None -O2 -Otime -S -apcs /interwork -Wb -Iinclude]
        CODE16

        AREA text, CODE, READONLY

__ct__4KikoFv PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        BNE      %24
        MOV      r0,#0xa4
        BL       __nw__FUi
        MOV      r4,r0
        BNE      %24
        MOV      r0,r4
18
        POP      {r4}
        POP      {r3}
        BX       r3
24
        MOV      r0,r4
        BL       __ct__7DefaultFv
        LDR      r0,_pool_1_404_0
        LDR      r2,_pool_1_404_16
        STR      r0,[r4,#0]
        ADR      r0,_pool_1_404_4
        STR      r0,[r4,#0x4c]
        MOV      r0,#5
        STRH     r0,[r4,#4]
        MOV      r0,r4
        ADD      r0,#0x80
        LDR      r1,[r0,#4]
        MOV      r3,#0x3c
        AND      r1,r2
        MOV      r2,#1
        LSL      r2,r2,#25
        ADD      r1,r1,r2
        STR      r1,[r0,#4]
        LDR      r1,[r0,#0xc]
        MOV      r2,#0xf
        LSL      r2,r2,#15
        BIC      r1,r2
        MOV      r2,#3
        LSL      r2,r2,#15
        ADD      r2,r1,r2
        MOV      r1,r4
        ADD      r1,#0x70
        STRB     r3,[r1,#0xd]
        MOV      r3,#0x14
        STRB     r3,[r1,#0xc]
        LDR      r1,[r0,#0]
        LDR      r3,_pool_1_404_20
        AND      r1,r3
        LDR      r3,_pool_1_404_24
        ADD      r1,r1,r3
        STR      r1,[r0,#0]
        LSR      r1,r2,#12
        LDR      r2,_pool_1_404_28
        LSL      r1,r1,#12
        ADD      r1,r1,r2
        LDR      r2,[r0,#8]
        LDR      r3,_pool_1_404_32
        AND      r2,r3
        LDR      r3,_pool_1_404_36
        ADD      r2,r2,r3
        STR      r2,[r0,#8]
        MOV      r2,#4
        MOV      r3,#0x97
        STRB     r2,[r3,r4]
        LSL      r2,r2,#10
        ORR      r1,r2
        STR      r1,[r0,#0xc]
        LDR      r0,_pool_1_404_40
        LDRH     r1,[r0,#4]
        STRH     r1,[r4,#8]
        LDRH     r1,[r0,#2]
        STRH     r1,[r4,#0xa]
        LDRH     r1,[r0,#4]
        STRH     r1,[r4,#0xc]
        LDRH     r1,[r0,#0]
        STRH     r1,[r4,#0xe]
        LDRH     r1,[r0,#0xa]
        STRH     r1,[r4,#0x18]
        LDRH     r1,[r0,#8]
        STRH     r1,[r4,#0x1a]
        LDRH     r1,[r0,#0xa]
        STRH     r1,[r4,#0x1c]
        LDRH     r0,[r0,#6]
        MOV      r1,#0xa0
        STRH     r0,[r4,#0x1e]
        MOV      r0,#0xcf
        STRH     r0,[r1,r4]
        MOV      r0,r4
        B        %18
        ENDP

__dt__4KikoFv PROC
        PUSH     {r3-r5,lr}
        MOV      r4,r0
        LDR      r0,_pool_1_404_0
        MOV      r5,r1
        MOV      r1,#0
        STR      r0,[r4,#0]
        MOV      r0,r4
        BL       __dt__7DefaultFv
        CMP      r5,#0
        BEQ      %202
        MOV      r0,r4
        BL       __dl__FPv
202
        POP      {r3-r5}
        POP      {r3}
        BX       r3
        ENDP

m04__4KikoFv PROC
        PUSH     {r3,lr}
        BL       m04__7DefaultFv
        ADD      sp,#4
        POP      {r3}
        BX       r3
        ENDP

m08__4KikoFv PROC
        PUSH     {r3,lr}
        BL       m08__7DefaultFv
        ADD      sp,#4
        POP      {r3}
        BX       r3
        ENDP

m10__4KikoFv PROC
        PUSH     {r3-r7,lr}
        MOV      r4,r0
        BL       rand
        MOV      r1,#0xa0
        LDRH     r1,[r1,r4]
        AND      r0,r1
        BNE      %288
        BL       rand
        BL       sub_80404B4
        ADD      r0,#1
        LSL      r0,r0,#24
        LSR      r0,r0,#24
        LSL      r1,r0,#1
        ADD      r1,r1,r0
        LDR      r3,_pool_1_404_40
        LSL      r1,r1,#1
        ADD      r0,r1,r3
        LDRH     r2,[r0,#4]
        STRH     r2,[r4,#0x18]
        LDRH     r2,[r0,#2]
        STRH     r2,[r4,#0x1a]
        LDRH     r0,[r0,#4]
        STRH     r0,[r4,#0x1c]
        LDRH     r0,[r3,r1]
        STRH     r0,[r4,#0x1e]
288
        MOV      r0,#0x9c
        LDR      r0,[r0,r4]
        CMP      r0,#0
        BNE      %392
        LDR      r7,_pool_1_404_44
        LDR      r5,[r4,#0x30]
        LDR      r0,[r7,#0]  ; gUnknown_03003EA0
        BL       sub_8000D5A
        LDR      r0,[r0,#0x20]
        LDR      r1,[r5,#0x10]
        LDR      r5,[r4,#0x2c]
        SUB      r0,r1,r0
        ASR      r0,r0,#3
        LSL      r6,r0,#16
        LSR      r6,r6,#16
        LDR      r0,[r7,#0]  ; gUnknown_03003EA0
        BL       sub_8000D5A
        LDR      r1,[r5,#0x44]
        LDR      r0,[r0,#0x28]
        LDR      r1,[r1,#4]
        LSL      r1,r1,#16
        LSR      r1,r1,#14
        ADD      r0,r0,r1
        LDR      r1,[r5,#0x48]
        LDR      r5,_pool_1_404_40
        SUB      r0,r1,r0
        ASR      r0,r0,#2
        LSL      r0,r0,#1
        ADD      r5,#0x18
        LDRH     r0,[r5,r0]
        CMP      r6,r0
        BEQ      %392
        LDR      r6,[r4,#0x2c]
        LDR      r0,[r7,#0]  ; gUnknown_03003EA0
        BL       sub_8000D5A
        LDR      r1,[r6,#0x44]
        LDR      r0,[r0,#0x28]
        LDR      r1,[r1,#4]
        LSL      r1,r1,#16
        LSR      r1,r1,#14
        ADD      r0,r0,r1
        LDR      r1,[r6,#0x48]
        SUB      r0,r1,r0
        ASR      r0,r0,#2
        LSL      r0,r0,#1
        LDRH     r1,[r5,r0]
        LDR      r0,[r4,#0x30]
        BL       sub_800065C
392
        MOV      r0,r4
        BL       m10__7DefaultFv
        POP      {r3-r7}
        POP      {r3}
        BX       r3
        ENDP
_pool_1_404_0
        DCD      __VTABLE__309Kiko
_pool_1_404_4
        DCB      "Kiko"
_pool_1_404_8
        DCB      " Gro"
_pool_1_404_12
        DCB      "up\0\0"
_pool_1_404_16
        DCD      0xf000ffff
_pool_1_404_20
        DCD      0xff8007ff
_pool_1_404_24
        DCD      0x0027b000
_pool_1_404_28
        DCD      0x00000505
_pool_1_404_32
        DCD      0xff8003ff
_pool_1_404_36
        DCD      0x00443800
_pool_1_404_40
        DCD      gUnknown_08051096
_pool_1_404_44
        DCD      gUnknown_03003EA0


        CODE32

        AREA __VTABLE__309Kiko, DATA, READONLY

        DCD      __dt__4KikoFv - __VTABLE__309Kiko
        DCD      m04__4KikoFv - __VTABLE__309Kiko
        DCD      m08__4KikoFv - __VTABLE__309Kiko
        DCD      m0C__7DefaultFv - __VTABLE__309Kiko
        DCD      m10__4KikoFv - __VTABLE__309Kiko
        DCD      m14__7DefaultFv - __VTABLE__309Kiko
        DCD      m18__7DefaultFv - __VTABLE__309Kiko
        DCD      m1C__7DefaultFv - __VTABLE__309Kiko
        DCD      m20__7DefaultFv - __VTABLE__309Kiko
        DCD      DamagePlayer__7DefaultFv - __VTABLE__309Kiko
        DCD      PlayerIframe__7DefaultFv - __VTABLE__309Kiko
        DCD      Attack__7DefaultFv - __VTABLE__309Kiko
        DCD      TakeDamage__7DefaultFv - __VTABLE__309Kiko
        DCD      Intersect__7DefaultFv - __VTABLE__309Kiko
        DCD      m38__7DefaultFv - __VTABLE__309Kiko
        DCD      m3C__7DefaultFv - __VTABLE__309Kiko
        DCD      m40__7DefaultFv - __VTABLE__309Kiko
        DCD      m44__7DefaultFv - __VTABLE__309Kiko
        DCD      Dying__7DefaultFv - __VTABLE__309Kiko
        DCD      Dead__7DefaultFv - __VTABLE__309Kiko


        EXPORT m10__4KikoFv
        EXPORT m08__4KikoFv
        EXPORT m04__4KikoFv
        EXPORT __dt__4KikoFv
        EXPORT __VTABLE__309Kiko
        EXPORT __ct__4KikoFv

        IMPORT Dead__7DefaultFv
        IMPORT Dying__7DefaultFv
        IMPORT m44__7DefaultFv
        IMPORT m40__7DefaultFv
        IMPORT m3C__7DefaultFv
        IMPORT m38__7DefaultFv
        IMPORT Intersect__7DefaultFv
        IMPORT TakeDamage__7DefaultFv
        IMPORT Attack__7DefaultFv
        IMPORT PlayerIframe__7DefaultFv
        IMPORT DamagePlayer__7DefaultFv
        IMPORT m20__7DefaultFv
        IMPORT m1C__7DefaultFv
        IMPORT m18__7DefaultFv
        IMPORT m14__7DefaultFv
        IMPORT m0C__7DefaultFv
        IMPORT sub_800065C
        IMPORT sub_8000D5A
        IMPORT sub_80404B4
        IMPORT rand
        IMPORT gUnknown_03003EA0
        IMPORT m10__7DefaultFv
        IMPORT m08__7DefaultFv
        IMPORT m04__7DefaultFv
        IMPORT __dt__7DefaultFv
        IMPORT __dl__FPv
        IMPORT __ct__7DefaultFv
        IMPORT __nw__FUi
        IMPORT gUnknown_08051096
        IMPORT ||Lib$$Request$$cpplib||, WEAK
        IMPORT ||Lib$$Request$$armlib||, WEAK

        KEEP ||BuildAttributes$$THUMB_ISAv1$M$A:L22$X:L11$S22$IW$~STKCKD$~SHL$OTIME$PRES8||
||BuildAttributes$$THUMB_ISAv1$M$A:L22$X:L11$S22$IW$~STKCKD$~SHL$OTIME$PRES8|| EQU 0

        ASSERT {ENDIAN} = "little"
        ASSERT {SWST} = {FALSE}
        ASSERT {NOSWST} = {TRUE}
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {NOT_SHL} = {TRUE}
        ASSERT {FULL_IEEE} = {FALSE}
        ASSERT {SHL1} = {FALSE}
        ASSERT {SHL2} = {FALSE}
        END
