; generated by Thumb C++ Compiler, ADS1.2 [Build 805]

; commandline [-fpu None -O2 -Otime -S -apcs /interwork -Wb -Iinclude]
        CODE16

        AREA text, CODE, READONLY


__dt__13dword_803ECB8Fv PROC
        PUSH     {r3,lr}
        LDR      r2,_pool_1_52_0
        LDR      r3,_pool_1_52_4
        STR      r2,[r0,#0]
        MOV      r2,#0
        STR      r2,[r3,#0]  ; gUnknown_03003E7C
        CMP      r1,#0
        BEQ      %46
        BL       __dl__FPv
46
        ADD      sp,#4
        POP      {r3}
        BX       r3
        ENDP
	ALIGN
_pool_1_52_0
        DCD      __VTABLE__354dword_803ECB8
	ALIGN
_pool_1_52_4
        DCD      gUnknown_03003E7C


        CODE32

        AREA __VTABLE__354dword_803ECB8, DATA, READONLY

        DCD      __dt__13dword_803ECB8Fv - __VTABLE__354dword_803ECB8


        EXPORT __dt__13dword_803ECB8Fv
        EXPORT __VTABLE__354dword_803ECB8

        IMPORT gUnknown_03003E7C
        IMPORT __dl__FPv
        IMPORT ||Lib$$Request$$cpplib||, WEAK
        IMPORT ||Lib$$Request$$armlib||, WEAK

        KEEP ||BuildAttributes$$THUMB_ISAv1$M$A:L22$X:L11$S22$IW$~STKCKD$~SHL$OTIME$PRES8||
||BuildAttributes$$THUMB_ISAv1$M$A:L22$X:L11$S22$IW$~STKCKD$~SHL$OTIME$PRES8|| EQU 0

        ASSERT {ENDIAN} = "little"
        ASSERT {SWST} = {FALSE}
        ASSERT {NOSWST} = {TRUE}
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {NOT_SHL} = {TRUE}
        ASSERT {FULL_IEEE} = {FALSE}
        ASSERT {SHL1} = {FALSE}
        ASSERT {SHL2} = {FALSE}
        END
