; generated by Thumb C++ Compiler, ADS1.2 [Build 805]

; commandline [-fpu None -O2 -Otime -S -apcs /interwork -Wb -Iinclude]
        CODE16

        AREA ||.text||, CODE, READONLY

__ct__13dword_803ECB8Fv PROC
        PUSH     {r3,lr}
        CMP      r0,#0
        BNE      |L1.16|
        MOV      r0,#4
        BL       __nw__FUi
        CMP      r0,#0
        BEQ      |L1.20|
|L1.16|
        LDR      r1,|L1.52|
        STR      r1,[r0,#0]
|L1.20|
        ADD      sp,#4
        POP      {r3}
        BX       r3
        ENDP

__dt__13dword_803ECB8Fv PROC
        PUSH     {r3,lr}
        LDR      r2,|L1.52|
        LDR      r3,|L1.52| + 4
        STR      r2,[r0,#0]
        MOV      r2,#0
        STR      r2,[r3,#0]  ; gUnknown_03003E7C
        CMP      r1,#0
        BEQ      |L1.46|
        BL       __dl__FPv
|L1.46|
        ADD      sp,#4
        POP      {r3}
        BX       r3
|L1.52| DATA
        DCD      __VTABLE__13dword_803ECB8
        DCD      gUnknown_03003E7C
        ENDP


        CODE32

        AREA __VTABLE__13dword_803ECB8, COMDEF, CODE, READONLY

        DCD      __dt__13dword_803ECB8Fv - {PC}


        EXPORT __dt__13dword_803ECB8Fv
        EXPORT __VTABLE__13dword_803ECB8
        EXPORT __ct__13dword_803ECB8Fv

        IMPORT gUnknown_03003E7C
        IMPORT __dl__FPv
        IMPORT __nw__FUi
        IMPORT ||Lib$$Request$$cpplib||, WEAK
        IMPORT ||Lib$$Request$$armlib||, WEAK

        KEEP ||BuildAttributes$$THUMB_ISAv1$M$A:L22$X:L11$S22$IW$~STKCKD$~SHL$OTIME$PRES8||
||BuildAttributes$$THUMB_ISAv1$M$A:L22$X:L11$S22$IW$~STKCKD$~SHL$OTIME$PRES8|| EQU 0

        ASSERT {ENDIAN} = "little"
        ASSERT {SWST} = {FALSE}
        ASSERT {NOSWST} = {TRUE}
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {NOT_SHL} = {TRUE}
        ASSERT {FULL_IEEE} = {FALSE}
        ASSERT {SHL1} = {FALSE}
        ASSERT {SHL2} = {FALSE}
        END
